#Numpy

In [46]:
import numpy as np
a=np.arange(10)
print(a.ndim)
print('item size: ',a.itemsize)
print('shape of an array',a.shape)

1
item size:  4
shape of an array (10,)


#Reshaping the array

In [45]:
a=np.arange(20).reshape(5,4)
print(a)
print('item size: ',a.itemsize)
print('shape of an array',a.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
item size:  4
shape of an array (5, 4)


#slicing an array

In [26]:
a=np.arange(30).reshape(5,6)
print(a[::])
print('\n')
print(a[:,4:6])

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


[[ 4  5]
 [10 11]
 [16 17]
 [22 23]
 [28 29]]


In [69]:
a=np.arange(20).reshape(4,5)
print(np.zeros((3,3)))
print('\n')
print(np.ones((4,5)))
print('\n')
print('Transposing')
print('\n')
print(np.transpose(a))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


Transposing


[[ 0  5 10 15]
 [ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]]


#character Manipulations

In [23]:
import numpy as np
print(np.char.add(['hello '],['hi']))
print(np.char.center('hi hello',20,fillchar="-"))
print(np.char.upper('Hello'))
print(np.char.lower('Hello'))
print(np.char.title('Hello'))

['hello hi']
------hi hello------
HELLO
hello
Hello


#Arithmetic Operations

In [49]:
a=np.arange(24).reshape(4,6)
b=np.arange(24).reshape(4,6)
print(a)
print('\n')
print(b)
print('\n''Addition','\n')
print(a+b)
print('\n''subtration','\n')
print(a-b)
print('\n''Multiplication','\n')
print(a*b)
print('\n''Division','\n')
print(np.divide(a,b))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]

Addition 

[[ 0  2  4  6  8 10]
 [12 14 16 18 20 22]
 [24 26 28 30 32 34]
 [36 38 40 42 44 46]]

subtration 

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]

Multiplication 

[[  0   1   4   9  16  25]
 [ 36  49  64  81 100 121]
 [144 169 196 225 256 289]
 [324 361 400 441 484 529]]

Division 

[[nan  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.]]


<ipython-input-49-672df278e5c5>:13: RuntimeWarning: invalid value encountered in true_divide
  print(np.divide(a,b))


#Numpy Exercise For Practise

In [86]:
a=np.arange(0,100,np.pi*3)
for x in np.nditer(a):
    x=x**2
    print(x)
print(a)

0.0
88.82643960980423
355.3057584392169
799.437956488238
1421.2230337568676
2220.660990245105
3197.751825952952
4352.495540880407
5684.89213502747
7194.941608394141
8882.64396098042
[ 0.          9.42477796 18.84955592 28.27433388 37.69911184 47.1238898
 56.54866776 65.97344573 75.39822369 84.82300165 94.24777961]
